AMQP_URI: amqp://guest:guest@localhost:5673

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
            formatter: default
    formatters:
        default:
            format: '%(asctime)s - %(levelname)s - %(message)s'
    root:
        level: INFO
        handlers: [console]
